/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HouseRouteImport } from './routes/house'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HouseCalculatorRouteImport } from './routes/HouseCalculator'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorsTileRouteImport } from './routes/calculators.tile'
import { Route as CalculatorsSteelRouteImport } from './routes/calculators.steel'
import { Route as CalculatorsSandRouteImport } from './routes/calculators.sand'
import { Route as CalculatorsRoomRouteImport } from './routes/calculators.room'
import { Route as CalculatorsPaintRouteImport } from './routes/calculators.paint'
import { Route as CalculatorsGravelRouteImport } from './routes/calculators.gravel'
import { Route as CalculatorsConcreteRouteImport } from './routes/calculators.concrete'
import { Route as CalculatorsBrickRouteImport } from './routes/calculators.brick'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPricesRouteImport } from './routes/_authenticated/prices'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCostSummaryRouteImport } from './routes/_authenticated/cost-summary'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCalculationsRouteImport } from './routes/_authenticated/calculations'

const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseCalculatorRoute = HouseCalculatorRouteImport.update({
  id: '/HouseCalculator',
  path: '/HouseCalculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsTileRoute = CalculatorsTileRouteImport.update({
  id: '/tile',
  path: '/tile',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsSteelRoute = CalculatorsSteelRouteImport.update({
  id: '/steel',
  path: '/steel',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsSandRoute = CalculatorsSandRouteImport.update({
  id: '/sand',
  path: '/sand',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsRoomRoute = CalculatorsRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsPaintRoute = CalculatorsPaintRouteImport.update({
  id: '/paint',
  path: '/paint',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsGravelRoute = CalculatorsGravelRouteImport.update({
  id: '/gravel',
  path: '/gravel',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsConcreteRoute = CalculatorsConcreteRouteImport.update({
  id: '/concrete',
  path: '/concrete',
  getParentRoute: () => CalculatorsRoute,
} as any)
const CalculatorsBrickRoute = CalculatorsBrickRouteImport.update({
  id: '/brick',
  path: '/brick',
  getParentRoute: () => CalculatorsRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricesRoute = AuthenticatedPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostSummaryRoute =
  AuthenticatedCostSummaryRouteImport.update({
    id: '/cost-summary',
    path: '/cost-summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculationsRoute =
  AuthenticatedCalculationsRouteImport.update({
    id: '/calculations',
    path: '/calculations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/HouseCalculator': typeof HouseCalculatorRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/house': typeof HouseRoute
  '/calculations': typeof AuthenticatedCalculationsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/cost-summary': typeof AuthenticatedCostSummaryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/calculators/brick': typeof CalculatorsBrickRoute
  '/calculators/concrete': typeof CalculatorsConcreteRoute
  '/calculators/gravel': typeof CalculatorsGravelRoute
  '/calculators/paint': typeof CalculatorsPaintRoute
  '/calculators/room': typeof CalculatorsRoomRoute
  '/calculators/sand': typeof CalculatorsSandRoute
  '/calculators/steel': typeof CalculatorsSteelRoute
  '/calculators/tile': typeof CalculatorsTileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/HouseCalculator': typeof HouseCalculatorRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/house': typeof HouseRoute
  '/calculations': typeof AuthenticatedCalculationsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/cost-summary': typeof AuthenticatedCostSummaryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/calculators/brick': typeof CalculatorsBrickRoute
  '/calculators/concrete': typeof CalculatorsConcreteRoute
  '/calculators/gravel': typeof CalculatorsGravelRoute
  '/calculators/paint': typeof CalculatorsPaintRoute
  '/calculators/room': typeof CalculatorsRoomRoute
  '/calculators/sand': typeof CalculatorsSandRoute
  '/calculators/steel': typeof CalculatorsSteelRoute
  '/calculators/tile': typeof CalculatorsTileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/HouseCalculator': typeof HouseCalculatorRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/house': typeof HouseRoute
  '/_authenticated/calculations': typeof AuthenticatedCalculationsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/cost-summary': typeof AuthenticatedCostSummaryRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/prices': typeof AuthenticatedPricesRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/calculators/brick': typeof CalculatorsBrickRoute
  '/calculators/concrete': typeof CalculatorsConcreteRoute
  '/calculators/gravel': typeof CalculatorsGravelRoute
  '/calculators/paint': typeof CalculatorsPaintRoute
  '/calculators/room': typeof CalculatorsRoomRoute
  '/calculators/sand': typeof CalculatorsSandRoute
  '/calculators/steel': typeof CalculatorsSteelRoute
  '/calculators/tile': typeof CalculatorsTileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/HouseCalculator'
    | '/auth'
    | '/calculators'
    | '/house'
    | '/calculations'
    | '/clients'
    | '/cost-summary'
    | '/dashboard'
    | '/favorites'
    | '/prices'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/calculators/brick'
    | '/calculators/concrete'
    | '/calculators/gravel'
    | '/calculators/paint'
    | '/calculators/room'
    | '/calculators/sand'
    | '/calculators/steel'
    | '/calculators/tile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/HouseCalculator'
    | '/auth'
    | '/calculators'
    | '/house'
    | '/calculations'
    | '/clients'
    | '/cost-summary'
    | '/dashboard'
    | '/favorites'
    | '/prices'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/calculators/brick'
    | '/calculators/concrete'
    | '/calculators/gravel'
    | '/calculators/paint'
    | '/calculators/room'
    | '/calculators/sand'
    | '/calculators/steel'
    | '/calculators/tile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/HouseCalculator'
    | '/auth'
    | '/calculators'
    | '/house'
    | '/_authenticated/calculations'
    | '/_authenticated/clients'
    | '/_authenticated/cost-summary'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/prices'
    | '/_authenticated/projects'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/calculators/brick'
    | '/calculators/concrete'
    | '/calculators/gravel'
    | '/calculators/paint'
    | '/calculators/room'
    | '/calculators/sand'
    | '/calculators/steel'
    | '/calculators/tile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HouseCalculatorRoute: typeof HouseCalculatorRoute
  AuthRoute: typeof AuthRoute
  CalculatorsRoute: typeof CalculatorsRouteWithChildren
  HouseRoute: typeof HouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/HouseCalculator': {
      id: '/HouseCalculator'
      path: '/HouseCalculator'
      fullPath: '/HouseCalculator'
      preLoaderRoute: typeof HouseCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/tile': {
      id: '/calculators/tile'
      path: '/tile'
      fullPath: '/calculators/tile'
      preLoaderRoute: typeof CalculatorsTileRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/steel': {
      id: '/calculators/steel'
      path: '/steel'
      fullPath: '/calculators/steel'
      preLoaderRoute: typeof CalculatorsSteelRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/sand': {
      id: '/calculators/sand'
      path: '/sand'
      fullPath: '/calculators/sand'
      preLoaderRoute: typeof CalculatorsSandRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/room': {
      id: '/calculators/room'
      path: '/room'
      fullPath: '/calculators/room'
      preLoaderRoute: typeof CalculatorsRoomRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/paint': {
      id: '/calculators/paint'
      path: '/paint'
      fullPath: '/calculators/paint'
      preLoaderRoute: typeof CalculatorsPaintRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/gravel': {
      id: '/calculators/gravel'
      path: '/gravel'
      fullPath: '/calculators/gravel'
      preLoaderRoute: typeof CalculatorsGravelRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/concrete': {
      id: '/calculators/concrete'
      path: '/concrete'
      fullPath: '/calculators/concrete'
      preLoaderRoute: typeof CalculatorsConcreteRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/calculators/brick': {
      id: '/calculators/brick'
      path: '/brick'
      fullPath: '/calculators/brick'
      preLoaderRoute: typeof CalculatorsBrickRouteImport
      parentRoute: typeof CalculatorsRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prices': {
      id: '/_authenticated/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof AuthenticatedPricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cost-summary': {
      id: '/_authenticated/cost-summary'
      path: '/cost-summary'
      fullPath: '/cost-summary'
      preLoaderRoute: typeof AuthenticatedCostSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculations': {
      id: '/_authenticated/calculations'
      path: '/calculations'
      fullPath: '/calculations'
      preLoaderRoute: typeof AuthenticatedCalculationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalculationsRoute: typeof AuthenticatedCalculationsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCostSummaryRoute: typeof AuthenticatedCostSummaryRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedPricesRoute: typeof AuthenticatedPricesRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalculationsRoute: AuthenticatedCalculationsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCostSummaryRoute: AuthenticatedCostSummaryRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedPricesRoute: AuthenticatedPricesRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CalculatorsRouteChildren {
  CalculatorsBrickRoute: typeof CalculatorsBrickRoute
  CalculatorsConcreteRoute: typeof CalculatorsConcreteRoute
  CalculatorsGravelRoute: typeof CalculatorsGravelRoute
  CalculatorsPaintRoute: typeof CalculatorsPaintRoute
  CalculatorsRoomRoute: typeof CalculatorsRoomRoute
  CalculatorsSandRoute: typeof CalculatorsSandRoute
  CalculatorsSteelRoute: typeof CalculatorsSteelRoute
  CalculatorsTileRoute: typeof CalculatorsTileRoute
}

const CalculatorsRouteChildren: CalculatorsRouteChildren = {
  CalculatorsBrickRoute: CalculatorsBrickRoute,
  CalculatorsConcreteRoute: CalculatorsConcreteRoute,
  CalculatorsGravelRoute: CalculatorsGravelRoute,
  CalculatorsPaintRoute: CalculatorsPaintRoute,
  CalculatorsRoomRoute: CalculatorsRoomRoute,
  CalculatorsSandRoute: CalculatorsSandRoute,
  CalculatorsSteelRoute: CalculatorsSteelRoute,
  CalculatorsTileRoute: CalculatorsTileRoute,
}

const CalculatorsRouteWithChildren = CalculatorsRoute._addFileChildren(
  CalculatorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HouseCalculatorRoute: HouseCalculatorRoute,
  AuthRoute: AuthRoute,
  CalculatorsRoute: CalculatorsRouteWithChildren,
  HouseRoute: HouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
